### ISSUE TITLE
Query by keyword

### ISSUE THREAD

**Issue by guolei329** [DevOps-Squads-Spring-2018/products#7]
**As a** User
**I need** to query items by keywords
**So that** I can know whether there is any product matches the query

**Assumptions:**
* The search results for keyword “query” should be accessed (but not modified) through the API call: GET /products/?keyword={query}

**Acceptance Criteria:**
```
When I issue a search with keyword “query”
And there are results that match that keyword
Then I get a list of items that match the keyword “query”
```

**Comment by yomancool** [comment]
should we take this to the technical debt label?
kind of a infrastructure?
