### ISSUE TITLE
Edit product description

### ISSUE THREAD

**Issue by yomancool** [DevOps-Squads-Spring-2018/products#8]
**As a** developer
**I need**  to update the items on the website
**So that** I can modify existing products info

**Assumptions:**
* Editing a product can be done through the API call: POST /products/{product-id}
* Original product info may represent from GET /products/{product-id}

**Acceptance Criteria:**
```
When I issue an edit with certain product
And there are options that I can modify the item
Then I get a updated info on that product
```

**Comment by guolei329** [comment]
I think in [RESTFul APIs](http://www.restapitutorial.com/lessons/restquicktips.html), update a specific resource is by calling PUT rather than POST.
